version: 2.1

jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/go:1.17
    services:
      - rabbitmq-server
    environment:
      - GO111MODULE=on
    steps:
      - run:
          name: Run tests
          command: go test ./... -coverprofile=coverage.out -covermode=atomic
      - run:
          name: Send codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  sample:
    jobs:
      - test
