version: 2.1

jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.17
      - image: rabbitmq
    environment:
      GO111MODULE=on
    steps:
      - checkout
      - restore_cache:
        keys:
          - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Wait for RabbitMQ to have started
          command: dockerize -wait tcp://localhost:5672 -timeout 1m
      - run:
          name: Run tests
          command: go test ./... -coverprofile=coverage.out -covermode=atomic
#      - codecov/upload:
#          file: {{ coverage_report_filepath }}

workflows:
  sample:
    jobs:
      - test
