version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2
environment:
  - GO111MODULE=on

jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/go:1.17
    services:
      - rabbitmq-server
    steps:
      - run:
          name: Run tests
          command: go test ./... -coverprofile=coverage.out -covermode=atomic
      - codecov/upload:
          file: {{ coverage_report_filepath }}

workflows:
  sample:
    jobs:
      - test
